CREATE TABLE listItems
(
    IIid SERIAL PRIMARY KEY,
    Lid INT REFERENCES list NOT NULL,
    IID INT REFERENCES items NOT NULL,
    LIdesired INT NOT NULL DEFAULT 1,
    LIpurchases INT NOT NULL DEFAULT 0
);